default:
  image: maven:3.9-eclipse-temurin-17

stages:
  - build
  - test

mvn-build:
  stage: build
  script:
    - cd routing_app
    - mvn compile
  only:
    changes:
      - routing_app/**/*

mvn-test:
  stage: test
  script:
    - cd routing_app
    - mvn test
  only:
    changes:
      - routing_app/**/*
